version: 0.2
phases:
  install:
    commands:
      #- sudo apt-get update
      - apt-get install xz-utils
      #- sudo apt-get -y upgrade
      - cd /tmp
      - wget https://nodejs.org/dist/v8.12.0/node-v8.12.0-linux-x64.tar.xz
      - tar -xf node-v8.12.0-linux-x64.tar.xz
      - mkdir -p /usr/local/nodejs
      - mv node-v8.12.0-linux-x64/* /usr/local/nodejs
      - cd $CODEBUILD_SRC_DIR
      - pwd
      - export PATH=$PATH:/usr/local/nodejs/bin
      - npm install serverless -g              
      - cd serverless
      - pwd && ls -lrth
      - npm install -g newman
      - ls -lrth
      - cd ..
  build:
    commands:
      - pwd && ls -lrth
      - cd api && pwd
      - cd CICD && ls -lrth
      - mvn clean install
      - cd ..
      - cd ..
      - pwd
      #- put UI build command
      - ls -lrth
      - cd serverless
      - serverless deploy --stage dev 
      - cd ..
  post_build:
    commands:
      - ls -lrth
      - newman run TMP.postman_collection.json