version: 0.2
phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get -y upgrade
      - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - cd serverless
      - pwd
      - ls -lrth 
      - npm install serverless
      - npm install serverless-s3-sync
      - npm install serverless-cloudwatch-dashboard
      - ls -lrth
      - cd ..
  build:
    commands:
      - pwd 
      - ls -lrth
      - cd api
      - pwd
      - cd CICD
      - pwd
      - ls -lrth
      - mvn clean install
      - cd ..
      - cd ..
      - pwd
      #- put UI build command
      - ls -lrth
      - cd serverless
      #Start Delete later as only for test
      - ls -lrth
      - cd node_modules
      - ls -lrth
      - cd ..
      - ls -lrth
      #End Delete later section
      - serverless
      - serverless deploy --stage dev 
#11  post_build:
 #   commands:
 #     - . ./test.sh