version: 0.1
phases:
  install:
    commands:
      - pwd 
      - cd api/CICD
      - pwd
      - ls -lrth
      - mvn clean install
      - cd ../..
      #- put UI build command
      - cd serverless
      - sudo apt-get update
      - sudo apt-get -y upgrade
      - curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm install -g serverless-s3-sync
      - npm install -g serverless-cloudwatch-dashboard
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage dev | tee deploy.out
#11  post_build:
 #   commands:
 #     - . ./test.sh