version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless-s3-sync
      - serverless-cloudwatch-dashboard
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage dev | tee deploy.out
#11  post_build:
 #   commands:
 #     - . ./test.sh